FROM nvidia/cuda:11.4.0-cudnn8-runtime-ubuntu20.04
FROM python:3.8.0-slim-buster
RUN apt update \
    && apt install -y --no-install-recommends \
    curl \
    ca-certificates \
    bash-completion \
    libgomp1 \
    g++ \
    gcc \
    git \
    make \
    libopenblas-dev \
    python3-tk \
    && apt-get autoremove -y \
    && apt-get autoclean \
    && apt-get clean

ENV POETRY_VERSION="1.2.0"
ENV POETRY_CACHE /work/.cache/poetry
ENV POETRY_HOME /usr/local/
ENV POETRY_VIRTUALENVS_PATH=$POETRY_CACHE

RUN curl -sSL https://install.python-poetry.org | python -

ENV SHELL /bin/bash
ENV PIP_CACHE_DIR /work/.cache/pip
ENV JUPYTER_RUNTIME_DIR /work/.cache/jupyter/runtime
ENV JUPYTER_CONFIG_DIR /work/.cache/jupyter/config

CMD ["bash", "-l"]