# Name of workflow
name: "CI pytest"

# Define trigger
on: push

# Cancel the workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Job
  build-and-deploy:
    runs-on: ubuntu-latest
    # define task
    steps:
      # 1. get content
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      # 2. run pytest
      - name: "Run env"
        run: |
          make env
      # 2. run pytest
      - name: "Run pytest"
        run: |
          make ci-pytest
      # 3. run generate docs
      - name: "Test generate docs"
        run: |
          make docs
      # 4. run linter
      - name: "Linter"
        run: |
          make lint || exit 1
      # 6. run Commit linter
      - name: "Commit linter"
        uses: wagoid/commitlint-github-action@v4 # https://github.com/wagoid/commitlint-github-action

