# Name of workflow
name: "CI pytest"

# Define trigger
on: push

jobs:

  # Job
  build-and-deploy:
    runs-on: ubuntu-latest

    # define task
    steps:
      # 1. get content
      - name: "Run pytest"
        run: |
          make

