# Name of workflow
name: "Build and deploy Github pages"

# Define trigger
on: push

jobs:

  # Job
  build-and-deploy:
    runs-on: ubuntu-latest

    # define task
    steps:
      # 1. get content
      - name: "Run pytest"
        run: |
          make ci

